name: managment
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  syncfusion_flutter_charts: ^20.2.44
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  appwrite: ^11.0.1
  provider: ^6.1.1

dev_dependencies: 
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  fonts: 
    - family: s
      fonts: 
        - asset: fonts/Roboto-Regular.ttf
  uses-material-design: true

